export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_FAILURE = "FETCH_COLLECTION_FAILURE";

export const FETCH_BY_UPC = "FETCH_BY_UPC";
export const FETCH_BY_UPC_SUCCESS = "FETCH_BY_UPC_SUCCESS";
export const FETCH_BY_UPC_FAILURE = "FETCH_BY_UPC_FAILURE";

export const SEARCH_FOR_GAME = "SEARCH_FOR_GAME";
export const SEARCH_FOR_GAME_SUCCESS = "SEARCH_FOR_GAME_SUCCESS";
export const SEARCH_FOR_GAME_FAILURE = "SEARCH_FOR_GAME_FAILURE";

export const ADD_ITEM = "ADD_ITEM";
export const DEL_ITEM = "DEL_ITEM";
