export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_COLLECTION_FAILURE = "FETCH_COLLECTION_FAILURE";

export const ADD_ITEM = "ADD_ITEM";
export const DEL_ITEM = "DEL_ITEM";
